# Data Processing

In [1]:
#import the necessary libraries for data analysis and visualization.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

In [2]:
#load the datasets for Douala and Maroua into pandas DataFrames.

douala = pd.read_csv("Data/Raw/Douala_Dataset.csv", skiprows=15)
maroua = pd.read_csv("Data/Raw/Maroua_Dataset.csv", skiprows=15)

In [3]:
#inspect the various datasets to understand their structure, dimensions, and the types of data they contain.
print("DOUALA")
print(douala.head())

print("MAROUA")
print(maroua.head())

DOUALA
   YEAR  MO  DY  HR  ALLSKY_SFC_SW_DWN  ALLSKY_SFC_SW_DNI  ALLSKY_SFC_SW_DIFF  \
0  2020   1   1   0                0.0                0.0                 0.0
1  2020   1   1   1                0.0                0.0                 0.0
2  2020   1   1   2                0.0                0.0                 0.0
3  2020   1   1   3                0.0                0.0                 0.0
4  2020   1   1   4                0.0                0.0                 0.0

     T2M   RH2M  PRECTOTCORR  WS10M
0  25.22  93.75          0.0   0.59
1  25.25  92.37          0.0   0.37
2  25.18  91.55          0.0   0.35
3  25.05  91.26          0.0   0.29
4  24.86  91.38          0.0   0.14
MAROUA
   YEAR  MO  DY  HR  ALLSKY_SFC_SW_DWN  ALLSKY_SFC_SW_DNI  ALLSKY_SFC_SW_DIFF  \
0  2020   1   1   0                0.0                0.0                 0.0
1  2020   1   1   1                0.0                0.0                 0.0
2  2020   1   1   2                0.0                0.0                 0.0
3  2020   1   1   3                0.0                0.0                 0.0
4  2020   1   1   4                0.0                0.0                 0.0

     T2M   RH2M  PRECTOTCORR  WS10M
0  19.53  22.81          0.0   5.19
1  18.66  24.00          0.0   5.14
2  17.88  25.20          0.0   5.12
3  17.17  26.52          0.0   5.18
4  16.50  27.93          0.0   5.24

In [4]:
print("Douala Shape:", douala.shape)
print("Maroua Shape:", maroua.shape)

Douala Shape: (56256, 11)
Maroua Shape: (56256, 11)

In [5]:
print(douala.columns)

Index(['YEAR', 'MO', 'DY', 'HR', 'ALLSKY_SFC_SW_DWN', 'ALLSKY_SFC_SW_DNI',
       'ALLSKY_SFC_SW_DIFF', 'T2M', 'RH2M', 'PRECTOTCORR', 'WS10M'],
      dtype='object')

In [6]:
# check the data types and non-null counts of Doaula
douala.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56256 entries, 0 to 56255
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   YEAR                56256 non-null  int64
 1   MO                  56256 non-null  int64
 2   DY                  56256 non-null  int64
 3   HR                  56256 non-null  int64
 4   ALLSKY_SFC_SW_DWN   56256 non-null  float64
 5   ALLSKY_SFC_SW_DNI   56256 non-null  float64
 6   ALLSKY_SFC_SW_DIFF  56256 non-null  float64
 7   T2M                 56256 non-null  float64
 8   RH2M                56256 non-null  float64
 9   PRECTOTCORR         56256 non-null  float64
 10  WS10M               56256 non-null  float64
dtypes: float64(7), int64(4)
memory usage: 4.7 MB

In [7]:
# check the data types and non-null counts of Maroua
maroua.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56256 entries, 0 to 56255
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   YEAR                56256 non-null  int64
 1   MO                  56256 non-null  int64
 2   DY                  56256 non-null  int64
 3   HR                  56256 non-null  int64
 4   ALLSKY_SFC_SW_DWN   56256 non-null  float64
 5   ALLSKY_SFC_SW_DNI   56256 non-null  float64
 6   ALLSKY_SFC_SW_DIFF  56256 non-null  float64
 7   T2M                 56256 non-null  float64
 8   RH2M                56256 non-null  float64
 9   PRECTOTCORR         56256 non-null  float64
 10  WS10M               56256 non-null  float64
dtypes: float64(7), int64(4)
memory usage: 4.7 MB

In [8]:
# check missing values in Douala
print("Missing values in Douala:")
print(douala.isnull().sum())

# check missing values in Maroua
print("\nMissing values in Maroua:")
print(maroua.isnull().sum())

Missing values in Douala:
YEAR                  0
MO                    0
DY                    0
HR                    0
ALLSKY_SFC_SW_DWN     0
ALLSKY_SFC_SW_DNI     0
ALLSKY_SFC_SW_DIFF    0
T2M                   0
RH2M                  0
PRECTOTCORR           0
WS10M                 0
dtype: int64

Missing values in Maroua:
YEAR                  0
MO                    0
DY                    0
HR                    0
ALLSKY_SFC_SW_DWN     0
ALLSKY_SFC_SW_DNI     0
ALLSKY_SFC_SW_DIFF    0
T2M                   0
RH2M                  0
PRECTOTCORR           0
WS10M                 0
dtype: int64

In [9]:
# check for duplicates in both datasets
print("Douala duplicates:", douala.duplicated().sum())
print("Maroua duplicates:", maroua.duplicated().sum())

Douala duplicates: 0
Maroua duplicates: 0

In [10]:
# create a datetime column in both datasets by combining the YEAR, MO, DY, and HR columns.
douala["datetime"] = pd.to_datetime(
    douala["YEAR"].astype(str) + "-" +
    douala["MO"].astype(str) + "-" +
    douala["DY"].astype(str) + " " +
    douala["HR"].astype(str) + ":00"
)

In [11]:
# create a datetime column in both datasets by combining the YEAR, MO, DY, and HR columns.
maroua["datetime"] = pd.to_datetime(
    maroua["YEAR"].astype(str) + "-" +
    maroua["MO"].astype(str) + "-" +
    maroua["DY"].astype(str) + " " +
    maroua["HR"].astype(str) + ":00"
)

In [12]:
douala[["datetime"]].head()

             datetime
0 2020-01-01 00:00:00
1 2020-01-01 01:00:00
2 2020-01-01 02:00:00
3 2020-01-01 03:00:00
4 2020-01-01 04:00:00

In [13]:
# describe the datasets to get a statistical summary of the numerical columns
douala.describe()

,YEAR,MO,DY,HR,ALLSKY_SFC_SW_DWN,ALLSKY_SFC_SW_DNI,ALLSKY_SFC_SW_DIFF,T2M,RH2M,PRECTOTCORR,WS10M,datetime
count,56256.000000,56256.000000,56256.000000,56256.000000,56256.000000,56256.000000,56256.000000,56256.000000,56256.000000,56256.000000,56256.000000,56256
mean,2022.726536,6.295648,15.719283,11.500000,100.243051,5.365836,26.041369,26.483615,86.171058,6.290816,1.333864,2023-03-17 23:30:00
min,2020.000000,1.000000,1.000000,0.000000,-999.000000,-999.000000,-999.000000,17.180000,28.270000,0.000000,0.010000,2020-01-01 00:00:00
25%,2021.000000,3.000000,8.000000,5.750000,0.000000,0.000000,0.000000,24.360000,76.310000,0.460000,1.020000,2021-08-08 23:45:00
50%,2023.000000,6.000000,16.000000,11.500000,0.000000,0.000000,0.000000,25.650000,93.030000,2.420000,1.260000,2023-03-17 23:30:00
75%,2024.000000,9.000000,23.000000,17.250000,313.642500,79.880000,187.985000,28.460000,97.420000,6.660000,1.590000,2024-10-23 23:15:00
max,2026.000000,12.000000,31.000000,23.000000,1002.530000,1106.640000,571.930000,39.620000,100.000000,427.810000,4.260000,2026-06-01 23:00:00
std,1.863272,3.463647,8.801628,6.922248,372.927382,294.408598,296.401545,2.815739,14.033297,13.536470,0.554255,NaN

In [14]:
maroua.describe()

,YEAR,MO,DY,HR,ALLSKY_SFC_SW_DWN,ALLSKY_SFC_SW_DNI,ALLSKY_SFC_SW_DIFF,T2M,RH2M,PRECTOTCORR,WS10M,datetime
count,56256.000000,56256.000000,56256.000000,56256.000000,56256.000000,56256.000000,56256.000000,56256.000000,56256.000000,56256.000000,56256.000000,56256
mean,2022.726536,6.295648,15.719283,11.500000,164.455061,98.187502,31.131700,28.459923,43.841352,1.877282,3.528619,2023-03-17 23:30:00
min,2020.000000,1.000000,1.000000,0.000000,-999.000000,-999.000000,-999.000000,12.390000,2.570000,0.000000,0.010000,2020-01-01 00:00:00
25%,2021.000000,3.000000,8.000000,5.750000,0.000000,0.000000,0.000000,23.970000,17.260000,0.000000,2.230000,2021-08-08 23:45:00
50%,2023.000000,6.000000,16.000000,11.500000,0.000000,0.000000,0.000000,27.740000,36.085000,0.000000,3.360000,2023-03-17 23:30:00
75%,2024.000000,9.000000,23.000000,17.250000,463.212500,301.140000,191.975000,32.730000,70.810000,0.560000,4.670000,2024-10-23 23:15:00
max,2026.000000,12.000000,31.000000,23.000000,1114.500000,1185.230000,674.750000,45.420000,100.000000,385.620000,12.370000,2026-06-01 23:00:00
std,1.863272,3.463647,8.801628,6.922248,441.525767,380.929387,299.621302,5.983310,29.162463,8.361769,1.659466,NaN

In [15]:
# check for negative values in the THIS TABLES for Douala
for col in [
    "ALLSKY_SFC_SW_DWN",
    "ALLSKY_SFC_SW_DNI",
    "ALLSKY_SFC_SW_DIFF"
]:
    print(col)
    print((douala[col] < 0).sum())

ALLSKY_SFC_SW_DWN
3672
ALLSKY_SFC_SW_DNI
3672
ALLSKY_SFC_SW_DIFF
3672

In [16]:
# check for negative values in the THIS TABLES for Maroua
for col in [
    "ALLSKY_SFC_SW_DWN",
    "ALLSKY_SFC_SW_DNI",
    "ALLSKY_SFC_SW_DIFF"
]:
    print(col)
    print((maroua[col] < 0).sum())

ALLSKY_SFC_SW_DWN
3672
ALLSKY_SFC_SW_DNI
3672
ALLSKY_SFC_SW_DIFF
3672

In [17]:
# CHECKING THE MINIMUM VALUES IN THE TABLE FOR DOUALA
print(douala["ALLSKY_SFC_SW_DWN"].min())
print(douala["ALLSKY_SFC_SW_DNI"].min())
print(douala["ALLSKY_SFC_SW_DIFF"].min())

-999.0
-999.0
-999.0

In [18]:
# check for negative values in the THIS TABLES for Maroua
print(maroua["ALLSKY_SFC_SW_DWN"].min())
print(maroua["ALLSKY_SFC_SW_DNI"].min())
print(maroua["ALLSKY_SFC_SW_DIFF"].min())

-999.0
-999.0
-999.0

In [19]:
# remove rows with negative values in the THIS TABLES for Douala
douala = douala[
    (douala["ALLSKY_SFC_SW_DWN"] >= 0) &
    (douala["ALLSKY_SFC_SW_DNI"] >= 0) &
    (douala["ALLSKY_SFC_SW_DIFF"] >= 0)
]

In [20]:
# remove rows with negative values in the THIS TABLES for Maroua
maroua = maroua[
    (maroua["ALLSKY_SFC_SW_DWN"] >= 0) &
    (maroua["ALLSKY_SFC_SW_DNI"] >= 0) &
    (maroua["ALLSKY_SFC_SW_DIFF"] >= 0)
]

In [21]:
# check the shapes of the datasets after removing negative values to see how many rows were removed.
print("After:", douala.shape)
print("After:", maroua.shape)

After: (52584, 12)
After: (52584, 12)

In [22]:
# check the range of datetime values in both datasets to understand the time span of the data.
print("\nDouala:")
print(douala["datetime"].min())
print(douala["datetime"].max())

print("\nMaroua:")
print(maroua["datetime"].min())
print(maroua["datetime"].max())

Douala:
2020-01-01 00:00:00
2025-12-30 23:00:00

Maroua:
2020-01-01 00:00:00
2025-12-30 23:00:00

In [25]:
# save the cleaned datasets to new CSV files for future use in modeling and analysis.
douala.to_csv("Data/Processed/Douala_Cleaned.csv", index=False)
maroua.to_csv("Data/Processed/Maroua_Cleaned.csv", index=False)

In [26]:
# create a combined dataset by concatenating the cleaned Douala and Maroua datasets, and add a new column to indicate the city for each row.
douala["City"] = "Douala"
maroua["City"] = "Maroua"

combined = pd.concat(
    [douala, maroua],
    ignore_index=True
)

combined.to_csv(
    "Data/Processed/Combined_Cameroon_Solar_Dataset.csv",
    index=False
)