#  Feature Engineering
### what is the use of feature engineering in machine learning?
### Feature engineering is the process of creating new features or modifying existing features in a dataset to improve

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [4]:
# load the datasets
douala = pd.read_csv("Data/Processed/Douala_Cleaned.csv")
maroua = pd.read_csv("Data/Processed/Maroua_Cleaned.csv")

In [5]:
maroua.head()

,YEAR,MO,DY,HR,ALLSKY_SFC_SW_DWN,ALLSKY_SFC_SW_DNI,ALLSKY_SFC_SW_DIFF,T2M,RH2M,PRECTOTCORR,WS10M,datetime
0,2020,1,1,0,0.0,0.0,0.0,19.53,22.81,0.0,5.19,2020-01-01 00:00:00
1,2020,1,1,1,0.0,0.0,0.0,18.66,24.00,0.0,5.14,2020-01-01 01:00:00
2,2020,1,1,2,0.0,0.0,0.0,17.88,25.20,0.0,5.12,2020-01-01 02:00:00
3,2020,1,1,3,0.0,0.0,0.0,17.17,26.52,0.0,5.18,2020-01-01 03:00:00
4,2020,1,1,4,0.0,0.0,0.0,16.50,27.93,0.0,5.24,2020-01-01 04:00:00

In [6]:
douala.head()

,YEAR,MO,DY,HR,ALLSKY_SFC_SW_DWN,ALLSKY_SFC_SW_DNI,ALLSKY_SFC_SW_DIFF,T2M,RH2M,PRECTOTCORR,WS10M,datetime
0,2020,1,1,0,0.0,0.0,0.0,25.22,93.75,0.0,0.59,2020-01-01 00:00:00
1,2020,1,1,1,0.0,0.0,0.0,25.25,92.37,0.0,0.37,2020-01-01 01:00:00
2,2020,1,1,2,0.0,0.0,0.0,25.18,91.55,0.0,0.35,2020-01-01 02:00:00
3,2020,1,1,3,0.0,0.0,0.0,25.05,91.26,0.0,0.29,2020-01-01 03:00:00
4,2020,1,1,4,0.0,0.0,0.0,24.86,91.38,0.0,0.14,2020-01-01 04:00:00

In [7]:
# check if all the dataset are loaded correctly
print("Douala:", douala.shape)
print("Maroua:", maroua.shape)

Douala: (52584, 12)
Maroua: (52584, 12)

In [1]:
# define the features to be used for modeling
features = [
    "ALLSKY_SFC_SW_DNI",
    "ALLSKY_SFC_SW_DIFF",
    "T2M",
    "RH2M",
    "WS10M",
    "PRECTOTCORR",
  
]

# define the target variable
target = "ALLSKY_SFC_SW_DWN"

In [8]:
# prepare the data for modeling by splitting into features and target variable, then into training and testing sets
X_douala = douala[features]
y_douala = douala[target]
X_train_douala, X_test_douala, y_train_douala, y_test_douala = train_test_split(
    X_douala, y_douala, test_size=0.2, random_state=42)

In [9]:
# prepare the data for modeling by splitting into features and target variable, then into training and testing sets
X_maroua = maroua[features]
y_maroua = maroua[target]
X_train_maroua, X_test_maroua, y_train_maroua, y_test_maroua = train_test_split(
    X_maroua, y_maroua, test_size=0.2, random_state=42)

In [10]:
# check the features and target variable
douala.to_csv("Data/Processed/Douala_Features.csv", index=False)

In [11]:
# save the prepared datasets to new CSV files for modeling
maroua.to_csv("Data/Processed/Maroua_Features.csv", index=False)

In [12]:
# check the features and target variable
print("Features:", features)
print("Target:", target)

Features: ['ALLSKY_SFC_SW_DNI', 'ALLSKY_SFC_SW_DIFF', 'T2M', 'RH2M', 'WS10M', 'PRECTOTCORR']
Target: ALLSKY_SFC_SW_DWN